# Generated by Django 4.2.27 on 2026-02-03 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerbreak',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='workerschedulerule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AddIndex(
            model_name='workerbreak',
            index=models.Index(fields=['worker', 'day_of_week'], name='staffing_wo_worker__a374dc_idx'),
        ),
        migrations.AddIndex(
            model_name='workerexception',
            index=models.Index(fields=['worker', 'date', 'type'], name='staffing_wo_worker__7be005_idx'),
        ),
        migrations.AddIndex(
            model_name='workerschedulerule',
            index=models.Index(fields=['worker', 'day_of_week', 'active'], name='staffing_wo_worker__07f1ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='workerschedulerule',
            constraint=models.UniqueConstraint(fields=('worker', 'day_of_week'), name='uniq_worker_day_schedule'),
        ),
    ]
