# Generated by Django 4.2.27 on 2026-02-01 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('default_fixed_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_categories', to='staffing.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('buffer_before_minutes', models.PositiveSmallIntegerField(default=0)),
                ('buffer_after_minutes', models.PositiveSmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('requirements', models.TextField(blank=True, default='')),
                ('assignment_type', models.CharField(choices=[('ROLE_BASED', 'Role based'), ('FIXED_WORKER', 'Fixed worker')], default='ROLE_BASED', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.servicecategory')),
                ('fixed_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_services', to='staffing.worker')),
            ],
            options={
                'indexes': [models.Index(fields=['active', 'category'], name='catalog_ser_active_4535fa_idx')],
            },
        ),
    ]
