# Generated by Django 4.2.27 on 2026-02-01 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No show')], default='RESERVED', max_length=20)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('created_channel', models.CharField(choices=[('CLIENT', 'Client'), ('STAFF', 'Staff')], default='CLIENT', max_length=20)),
                ('recommended_subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recommended_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recommended_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='booking.appointment')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='staffing.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('CASUAL', 'Casual'), ('FREQUENT', 'Frequent')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentServiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name_snapshot', models.CharField(max_length=120)),
                ('duration_minutes_snapshot', models.PositiveSmallIntegerField()),
                ('buffer_before_snapshot', models.PositiveSmallIntegerField(default=0)),
                ('buffer_after_snapshot', models.PositiveSmallIntegerField(default=0)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='booking.appointmentblock')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('RESCHEDULE', 'Reschedule'), ('CANCEL', 'Cancel'), ('STATUS_CHANGE', 'Status change'), ('PAYMENT_RECORDED', 'Payment recorded')], max_length=30)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('detail_json', models.JSONField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='booking.appointment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_audits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.customer'),
        ),
        migrations.AddIndex(
            model_name='appointmentblock',
            index=models.Index(fields=['worker', 'start_datetime'], name='booking_app_worker__c20052_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentblock',
            index=models.Index(fields=['worker', 'end_datetime'], name='booking_app_worker__7212fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentblock',
            unique_together={('appointment', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='appointmentaudit',
            index=models.Index(fields=['appointment', 'performed_at'], name='booking_app_appoint_2e111a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentaudit',
            index=models.Index(fields=['action', 'performed_at'], name='booking_app_action_004dfb_idx'),
        ),
    ]
