# Generated by Django 4.2.27 on 2026-02-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_appointment_paid_at_appointment_paid_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentblock',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointmentblock',
            constraint=models.UniqueConstraint(fields=('worker', 'start_datetime'), name='uniq_worker_start_datetime_block'),
        ),
    ]
