# Generated by Django 4.2.27 on 2026-02-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointmentblock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type', 'phone'], name='booking_cus_custome_ffb9d6_idx'),
        ),
    ]
